### ISSUE TITLE
VALUE_COUNTS with high NaN?

### ISSUE THREAD

**Issue by Prooffreader** [bacumin/Pandas_initial_profiler#3]
I wonder if it would be a good idea to have an option of showing VALUE_COUNTS ratios not including NaNs in certain circumstances; maybe if p(NaN) is above a certain threshold?

My suggestion would be to put it as an extra column, but leave the bar chart the way it is, because having big bars would be misleading.

**Comment by bacumin** [comment]
I'll add it as an optional feature. Non nan proportion is printed just after the bar chart in the value counts if vc_nonan=True.
